export let StudentData= {academicYear:"",academicTerm:"",detail:{ 
    agno: "",
    anA_OGR_NO: "",
    boluM_AD: "",
    boluM_KOD: "",
    caP_YANDAL_DURUM: "",
    cinsiyet: "",
    d_TARIH: "",
    danismaN_1: "",
    danismaN_2: "",
    epostA1: "",
    epostA2: "",
    fakultE_AD: "",
    fakultE_KOD: "",
    gsM1: "",
    kayiT_TARIH: "",
    ogR_ADI: "",
    ogR_NO: "",
    ogR_SOYAD: "",
    ogrencI_GELIS_SEKLI: "",
    ogrencI_STATU: "",
    ogrencI_SURE: "",
    ogreniM_TIP: "",
    okudugU_DONEM: "",
    okudugU_YIL: "",
    picture: "",
    prograM_AD: "",
    prograM_KOD: "",
    sinif: "1",
    tC_KIMLIK_NO: "",
    yoksiS_KOD: "",
    
  }}