
import { getLocales } from 'expo-localization';

export const LGWord = {

    tr: {
        duacat: "Dua Kategorileri",
        duaih: "İhticaç duyduğunuz Dua'ya buradan ulaşabilirsiniz.",
        blBig: "BİLGİ",
        uyeGiris: "Üye Ol / Giriş Yap",
        gd: "Gizli Dualar",
        geri: "Geri",
        acildi: "Açıldı",
        devami: "Devamı",
        etki: "Etki",
        duaUygulanis: "Dua Uygulanış",
        adim: "Adım",
        badimk: "Bu adım kilitli",
        kilkaldok: "Kilidi kaldırmak için dokunun",
        oncekiAdim: "Önceki Adım",
        sonrakiAdim: "Sonraki Adım",
        kilitAcilmadi: "Kilit Açılmadı",
        anahtarYetersiz: "Yeterli anahtarınız bulunmuyor",
        ihtiyacAnahtar: " adet anahtara ihtiyacınız var",
        anahtarAl: "Anahtar Al",
        vazgec: "Vazgeç",
        anahtarPaket: "Dua Anahtar Paketleri",
        anahtarDikkatli: "Anahtarları dikkatli kullan. İhtiyacın olmayan duayı açma.",
        anahtarIsraf: "İsrafın platformu yoktur İsraf israftır.",
        smallAnahtar: "Small Anahtar",
        mediumAnahtar: "Medium Anahtar",
        premiumAnahtar: "Premium Anahtar",
        hemenAl: "Hemen Al!",
        anahtar:"Anahtar",
        kayitOl: "Kayıt Ol",
        girisYap: "Giriş Yap",
        telGerekli: "Kullanıcı Adı",
        kayitFormu: "Kayıt Formu",
        email: "Email",
        telefonNo: "Telefon No",
        sifre: "Şifre",
        sifreTekrari: "Şifre Tekrarı",
        devamEt: "Devam Et",
        girisIcınTel: "Giriş yapmak için telefon no ve şifre girin",
        mevcutKullanici: "Bu Kullanıcı Zaten Mevcut. Başk Bir Kullanıcı Adı Giriniz",
        hata: "Hata",
        uyari: "Uyarı",
        eksikBilgi: "Eksik Bilgi",
        emailHatali: "Email bilgisi hatalı",
        sifreEslesmedi: "Şifreler Eşleşmedi. İki şifrede aynı olmalı",
        emailBos: "Email alanı boş bırakılamaz",
        telefonBos: "Telefon alanı boş bırakılamaz",
        ara: "Ara",
        phsearch: "Aşık etme, büyü bozma, vs...",
        aramaTemizle: "Aramayı Temizle",
        kayitBulunamadi: "Kayıt Bulunamadı",
        cumleBulunamadi: "Aradığınız kelime ile eşleşen herhangi bir kayıt bulunamadı",
        duaListesi: "Dua Listesi",
        kisilik: "Kişilik Analizi",
        kisiAnaliz: "Analiz Yapılacak Kişinin Bilgilerini Girin",
        dogumTarihi:"Doğum Tarihi",
        dogumSaati:"Doğum Saati(24)",
        erkek:"Erkek",
        kadin:"Kadın",
        boy:"Boy (CM)",
        anneYas:"Anne Yaşı",
        babaYas:" Baba Yaşı",
        hesapla:"Hesapla",
        duygusallik : "Duygusallık",
        sinir : "Sinir",
        irade : "İrade",
        ego : "Ego",
        merhamet : "Merhamet",
        sorumluluk : "Sorumluluk",
        sadakat : "Sadakat",
        saygi :"Saygı",
        dogumSaatiGir:"Doğum Saati Giriniz",
        kayitYapGirisYap:"Kayıt olmadan bu özellik kullanılamaz.",
        besyuzKoin:"İlk kulanımda 500 adet anahtara hediye edilir.",
        highAnahtar:"High Anahtar",
        kullaniciAdi:"Kullanıcı Adı",
        sureler: "Sureler",
        dinle: "Dinle",
        durdur: "Durdur",
        sesCalmaHatasi: "Ses oynatılırken bir hata oluştu.",
        dahaFazlaYok: "Tüm sûreler yüklendi",
        ayrinti: "Ayrıntı",
        gizle: "Gizle",
        yukleniyor: "Yükleniyor...",
        oynatiliyor: "Ses oynatılıyor",
        duraklatildi: "Ses duraklatıldı",
        aciklama: "Açıklama",
        ozelAlanim: "Niyet Alanım",
        bugunkuGorevler: "Bugünkü Görevler",
        gorevler: "Görevler",
        gecmis: "Geçmiş",
        analiz: "Analiz",
        profiliniOlustur: "Dua Planı Oluştur",
        hedefSec: "Hedeflerini seç",
        calismaSeviyesi: "Çalışma seviyesi",
        focusModu: "Odak modu",
        bildirimler: "Bildirimler",
        hafif: "Hafif",
        dengeli: "Dengeli",
        derin: "Derin",
        manevi: "Manevi",
        duygusal: "Duygusal",
        zihinsel: "Zihinsel",
        kategoriSec: "Kategori seç",
        duaSec: "Dua seç",
        planOnizleme: "Plan önizleme",
        planPreviewPlaceholder: "Dua seçtiğinde plan önizlemesi burada görünecek.",
        planiOlustur: "Şifa planını başlat",
        kaydet: "Kaydet",
        iptal: "İptal",
        planAciklamasi: "Plan Açıklaması",
        planDescriptionPlaceholder: "Bu plan için açıklama bulunmuyor.",
        arzulariniYaz: "Arzularını yaz",
        arzulariniYazAciklama: "İhtiyaçlarını veya yaşadığın durumu birkaç cümleyle anlat.",
        arzulariniYazPlaceholder: "Ör: Uyuyamıyorum, içimde huzursuzluk var...",
        arzulariniYazUyari: "Devam edebilmek için arzularını yazmalısın.",
        aiMatchInfo: "Yapay zekâ ifadeni analiz ederek sana en uygun dua planını otomatik belirler.",
        analizEdiliyor: "Analiz ediliyor...",
        eslesmeBulunamadi: "Şu an uygun bir dua bulunamadı. Lütfen farklı bir şekilde ifade etmeyi dene.",
        eslesmeBekleniyor: "Arzularınıza göre uygun plan aranıyor.",
        kategoriSecildi: "Kategori belirlendi",
        onerilenPlan: "Önerilen Plan",
        tamamlandi: "Tamamlandı",
        tamamlanmadi: "Tamamlanmadı",
        kacirildi: "Kaçırıldı",
        gorevTamamla: "Tamamlandı",
        gorevTasarimi: "Bugünkü reçeten hazır",
        bildirimIzinUyarisi: "Bildirim gönderebilmemiz için izin vermelisin",
        hicKayitYok: "Henüz bir kayıt bulunmuyor.",
        tamamlananGorev: "Tamamlanan görev",
        seri: "Seri",
        enSikYapilanlar: "En sık yaptıkların",
        analizOzeti: "Analiz özeti",
        analizTrend: "Günlük eğilim",
        tamamlamaOrani: "Tamamlama",
        tamamlanan: "Tamamlanan"
       


    },
    ar: {
        duacat: "تصنيفات الدعاء!",
        duaih: "يمكنك الوصول إلى الدعاء الذي تحتاجه من هنا.",
        blBig: "توجيه",
        uyeGiris: "سجل / سجل الدخول",
        gd: "الأدعية السرية",
        geri: "خلف",
        acildi: "فتح",
        devami: "المزيد",
        etki: "قوة",
        duaUygulanis: "طريقة الدعاء",
        adim: "خطوة",
        badimk: "هذه الخطوة مغلقة",
        kilkaldok: "لفتح القفل، اضغط هنا",
        oncekiAdim: "الخطوة السابقة",
        sonrakiAdim: "الخطوة التالية",
        kilitAcilmadi: "لم يتم فتح القفل",
        anahtarYetersiz: "لا توجد لديك مفاتيح كافية.",
        ihtiyacAnahtar: "قطعة مطلوبة.",
        anahtarAl: "احصل على المفتاح",
        vazgec: "إلغاء",
        anahtarPaket: "حزم مفاتيح فتح الأدعية",
        anahtarDikkatli: "استخدم المفاتيح بحذر. لا تفتح الدعاء الذي ليس لديك حاجة إليه.",
        anahtarIsraf: "لا منصة للإسراف. الإسراف هو الإسراف.",
        smallAnahtar: "مفتاح صغير",
        mediumAnahtar: "مفتاح متوسط",
        premiumAnahtar: "مفتاح بريميوم",
        hemenAl: "اشترِ الآن!",
        kayitOl: "سجل",
        girisYap: "تسجيل الدخول",
        telGerekli: "اسم المستخدم",
        kayitFormu: "نموذج التسجيل",
        email: "البريد الإلكتروني",
        telefonNo: "رقم الهاتف",
        sifre: "كلمة المرور",
        sifreTekrari: "تأكيد كلمة المرور",
        devamEt: "استمر",
        girisIcınTel: "أدخل رقم الهاتف وكلمة المرور لتسجيل الدخول",
        mevcutKullanici: "هذا المستخدم موجود بالفعل. الرجاء إدخال اسم مستخدم آخر",
        hata: "خطأ",
        uyari: "تحذير",
        eksikBilgi: "معلومات ناقصة",
        emailHatali: "البريد الإلكتروني غير صحيح",
        sifreEslesmedi: "كلمات المرور غير متطابقة. يجب أن تكون كلمتا المرور متطابقتين",
        emailBos: "لا يمكن ترك حقل البريد الإلكتروني فارغًا",
        telefonBos: "لا يمكن ترك حقل الهاتف فارغًا",
        ara: "بحث",
        phsearch: "جعل الحب، فك السحر، الخ...",
        aramaTemizle: "مسح البحث",
        kayitBulunamadi: "لم يتم العثور على تسجيل",
        cumleBulunamadi: "لم يتم العثور على أي تسجيل يتطابق مع الكلمة التي بحثت عنها.",
        duaListesi: "قائمة الدعاء.",
        kisilik: "تحليل الشخصية",
        kisiAnaliz: "أدخل معلومات الشخص الذي تريد إجراء تحليل شخصيته",
        dogumTarihi:"تاريخ الميلاد",
        dogumSaati:"وقت الميلاد (24)",
        erkek:"ذكر",
        kadin:"أنثى",
        boy:"الطول (سم)",
        anneYas:"عمر الأم",
        babaYas:"عمر الأب",
        hesapla:"احسب",
        duygusallik : "المشاعر",
        sinir : "الغضب",
        irade : "الإرادة",
        ego : "الأنا",
        merhamet : "الرحمة",
        sorumluluk : "المسؤولية",
        sadakat : "الوفاء",
        saygi :"الاحترام",
        dogumSaatiGir:"أدخل وقت الميلاد",
        kayitYapGirisYap:"بدون تسجيل، لا يمكن استخدام هذه الميزة.",
        besyuzKoin:"في استخدامها الأولي يُهدى 500 مفتاحًا.",
        anahtar:"مفتاح",
        highAnahtar:"المفتاح العالي",
        kullaniciAdi:"اسم المستخدم",
        sureler: "السور",
        dinle: "استمع",
        durdur: "إيقاف",
        sesCalmaHatasi: "حدث خطأ أثناء تشغيل الصوت.",
        dahaFazlaYok: "تم تحميل جميع السور",
        ayrinti: "تفاصيل",
        gizle: "إخفاء",
        yukleniyor: "جارٍ التحميل...",
        oynatiliyor: "التشغيل جارٍ",
        duraklatildi: "تم الإيقاف مؤقتًا",
        aciklama: "الوصف",
        ozelAlanim: "مساحتي الخاصة",
        bugunkuGorevler: "مهام اليوم",
        gorevler: "المهام",
        gecmis: "السجل",
        analiz: "التحليل",
        profiliniOlustur: "إنشاء خطة",
        hedefSec: "اختر أهدافك",
        calismaSeviyesi: "مستوى العمل",
        focusModu: "وضع التركيز",
        bildirimler: "الإشعارات",
        hafif: "خفيف",
        dengeli: "متوازن",
        derin: "عميق",
        manevi: "روحي",
        duygusal: "عاطفي",
        zihinsel: "ذهني",
        kategoriSec: "اختر الفئة",
        duaSec: "اختر الدعاء",
        planOnizleme: "معاينة الخطة",
        planPreviewPlaceholder: "ستظهر معاينة الخطة هنا بعد اختيار الدعاء.",
        planiOlustur: "ابدأ خطة الشفاء",
        kaydet: "حفظ",
        iptal: "إلغاء",
        planAciklamasi: "وصف الخطة",
        planDescriptionPlaceholder: "لا يوجد وصف لهذه الخطة.",
        arzulariniYaz: "اكتب احتياجاتك",
        arzulariniYazAciklama: "صف ما تحتاجه أو ما تعيشه ببضع جمل.",
        arzulariniYazPlaceholder: "مثال: لا أستطيع النوم، أشعر بعدم راحة...",
        arzulariniYazUyari: "يرجى كتابة احتياجاتك للمتابعة.",
        aiMatchInfo: "يقوم الذكاء الاصطناعي بتحليل كلماتك ليختار تلقائيًا الدعاء الأكثر ملاءمة لك.",
        analizEdiliyor: "جارٍ التحليل...",
        eslesmeBulunamadi: "لم يتم العثور على دعاء مناسب الآن. حاول بتعبير مختلف.",
        eslesmeBekleniyor: "يتم البحث عن خطة تناسب احتياجاتك.",
        kategoriSecildi: "تم تحديد الفئة",
        onerilenPlan: "الخطة المقترحة",
        tamamlandi: "اكتمل",
        tamamlanmadi: "لم يكتمل",
        kacirildi: "فات",
        gorevTamamla: "أُنجز",
        gorevTasarimi: "وُضعت وصفة يومك",
        bildirimIzinUyarisi: "يجب منح إذن التنبيهات",
        hicKayitYok: "لا توجد سجلات بعد.",
        tamamlananGorev: "المهام المكتملة",
        seri: "سلسلة الاستمرارية",
        enSikYapilanlar: "الأكثر تكرارًا",
        analizOzeti: "ملخص التحليل",
        analizTrend: "اتجاه الأيام",
        tamamlamaOrani: "نسبة الإكمال",
        tamamlanan: "مكتمل"
       

    }



};


var lcl;
try {
    lcl = getLocales();
} catch (e) {
    lcl = [];
}
export const DeviceLanguage = (Array.isArray(lcl) && lcl.length > 0 && lcl[0]) ? lcl[0].languageCode : "tr"

export const LangApp = (word = "") => {



    var ln = (Array.isArray(lcl) && lcl.length > 0 && lcl[0]) ? lcl[0].languageCode : "tr"
    if (ln != "ar") {
        ln = "tr"
    }
    // When a value is missing from a language it'll fallback to another language with the key present.
    var sas = LGWord[ln][word]

    return sas + ""
}
